// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gamma_cpp
Rcpp::List gamma_cpp(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, double tol, int maxiter);
RcppExport SEXP _irls_gamma_cpp(SEXP XSEXP, SEXP ySEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_cpp(X, y, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// gammas_new
Eigen::MatrixXd gammas_new(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, double tol, int maxiter, bool parallel);
RcppExport SEXP _irls_gammas_new(SEXP XSEXP, SEXP ySEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(gammas_new(X, y, tol, maxiter, parallel));
    return rcpp_result_gen;
END_RCPP
}
// logis_new
Eigen::MatrixXd logis_new(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, double tol, int maxiter, bool parallel);
RcppExport SEXP _irls_logis_new(SEXP XSEXP, SEXP ySEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(logis_new(X, y, tol, maxiter, parallel));
    return rcpp_result_gen;
END_RCPP
}
// logistic_cpp
Rcpp::List logistic_cpp(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, double tol, int maxiter);
RcppExport SEXP _irls_logistic_cpp(SEXP XSEXP, SEXP ySEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(logistic_cpp(X, y, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// poiss_new
Eigen::MatrixXd poiss_new(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, double tol, int maxiter, bool parallel);
RcppExport SEXP _irls_poiss_new(SEXP XSEXP, SEXP ySEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP parallelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type parallel(parallelSEXP);
    rcpp_result_gen = Rcpp::wrap(poiss_new(X, y, tol, maxiter, parallel));
    return rcpp_result_gen;
END_RCPP
}
// poisson_cpp
Rcpp::List poisson_cpp(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, double tol, int maxiter);
RcppExport SEXP _irls_poisson_cpp(SEXP XSEXP, SEXP ySEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(poisson_cpp(X, y, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_irls_gamma_cpp", (DL_FUNC) &_irls_gamma_cpp, 4},
    {"_irls_gammas_new", (DL_FUNC) &_irls_gammas_new, 5},
    {"_irls_logis_new", (DL_FUNC) &_irls_logis_new, 5},
    {"_irls_logistic_cpp", (DL_FUNC) &_irls_logistic_cpp, 4},
    {"_irls_poiss_new", (DL_FUNC) &_irls_poiss_new, 5},
    {"_irls_poisson_cpp", (DL_FUNC) &_irls_poisson_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_irls(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
