# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gamma_cpp <- function(X, y, tol = 1e-8, maxiter = 100L) {
    .Call('_irls_gamma_cpp', PACKAGE = 'irls', X, y, tol, maxiter)
}

gammas_new <- function(X, y, tol = 1e-8, maxiter = 100L, parallel = FALSE) {
    .Call('_irls_gammas_new', PACKAGE = 'irls', X, y, tol, maxiter, parallel)
}

logis_new <- function(X, y, tol = 1e-6, maxiter = 100L, parallel = FALSE) {
    .Call('_irls_logis_new', PACKAGE = 'irls', X, y, tol, maxiter, parallel)
}

logistic_cpp <- function(X, y, tol = 1e-6, maxiter = 100L) {
    .Call('_irls_logistic_cpp', PACKAGE = 'irls', X, y, tol, maxiter)
}

poiss_new <- function(X, y, tol = 1e-6, maxiter = 100L, parallel = FALSE) {
    .Call('_irls_poiss_new', PACKAGE = 'irls', X, y, tol, maxiter, parallel)
}

poisson_cpp <- function(X, y, tol = 1e-6, maxiter = 100L) {
    .Call('_irls_poisson_cpp', PACKAGE = 'irls', X, y, tol, maxiter)
}

